<?php
require_once ('Controller.php');

class AdminController extends Controller
{
    function index($content = 'table')
    {
        return parent::index('admin-table'); // TODO: Change the autogenerated stub
    }

    function edit(){
        $task = new Task();
        $_GET['id'] = intval($_GET['id']);
        $fill=$task->find($_GET['id']);

        if(!empty($fill)){

            if(isset($_POST['text'])){
                $_POST['text']=htmlspecialchars(strip_tags(trim($_POST['text'])));
                if ($_POST['status']!='1')
                    $_POST['status']='0';
                $task->update($_GET['id'],$_POST['text'],$_POST['status']);
                header('Location: http://bbee.kl.com.ua/admin/edit.php?id='.$_GET['id'].'&rand='.rand(1000,9999));
            }



            $mainHTML.= include $_SERVER['DOCUMENT_ROOT'].'/view/admin-form.php';

            if(isset($_GET['rand']))
                $mainHTML.= "<div class=\"alert alert-success\" role=\"alert\">Все хорошо</div>";

            $this->html = include $_SERVER['DOCUMENT_ROOT'].'/view/app.php';
        }
        else
            header('Location: http://bbee.kl.com.ua/admin/index.php');

        return $this;
    }
}