<?php
require_once ('IndexController.php');

/**
 * Class AdminController - admin part
 */
class AdminController extends IndexController
{

    /**Call index page of admin
     * @param string $content
     * @return IndexController
     * @throws Twig_Error_Loader
     * @throws Twig_Error_Runtime
     * @throws Twig_Error_Syntax
     */
    function index($content = 'table')
    {
        return parent::index('admin-table'); // TODO: Change the autogenerated stub
    }

    /**
     * Edit task page
     * @return $this
     * @throws Twig_Error_Loader
     * @throws Twig_Error_Runtime
     * @throws Twig_Error_Syntax
     */
    function edit(){
        $task = new Task();
        $_GET['id'] = intval($_GET['id']);
        $fill=$task->find($_GET['id']);

        if(!empty($fill)){

            if(isset($_POST['text'])){
                $_POST['text']=htmlspecialchars(strip_tags(trim($_POST['text'])),ENT_QUOTES);
                if ($_POST['status']!='1')
                    $_POST['status']='0';
                $task->update($_GET['id'],$_POST['text'],$_POST['status']);
                header('Location: http://'.$_SERVER['HTTP_HOST'].'/admin/edit.php?id='.$_GET['id'].'&rand='.rand(1000,9999));
            }

            $this->HTML($this->view('admin-form',['fill' => $fill, 'rand' => $_GET['rand']]));
        }
        else
            header('Location: http://'.$_SERVER['HTTP_HOST'].'/admin/index.php');

        return $this;
    }
}